### ISSUE TITLE
TextMate bundle

### ISSUE THREAD

**Issue by dmeijboom** [dmeijboom/atom#3]
Currently, I added a text mate bundle to get basic syntax highlighting in my IDE (IntelliJ Ultimate). It's based on another bundle and works "ok-ish" but a lot of things are not working or broken.. It probably has to be rewritten from scratch.

 I want to make sure most basics are working, such as:

**Todo**

- [ ] Comments (first character is not interpreted correctly)
- [ ] Function calls (with keywords)
- [ ] Casts
- [ ] Core type names
- [ ] Closures
- [ ] Maps
- [ ] Formatted Strings

**Comment by IssueHuntBot** [comment]
[@dmeijboom](https://issuehunt.io/u/dmeijboom) has funded $50.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/385495055/issues/3) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/385495055/issues/3).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/r/new) on IssueHunt to raise funds.
